---
- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  loop:
    - "{{ openldap_configuration_directory }}"
    - "{{ openldap_configuration_directory }}/umc/gateway"
    - "{{ openldap_configuration_directory }}/umc/web"
    - "{{ openldap_configuration_directory }}/umc/server"
    - "{{ openldap_secrets_directory }}"
    - "{{ openldap_docker_compose_directory }}"

- name: Copy environment files and ucr files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ openldap_configuration_directory }}/{{ item.dest }}"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - src: env/openldap.env.j2
      dest: openldap.env
    - src: env/udm-rest.env.j2
      dest: udm-rest.env
    - src: env/umc-web.env.j2
      dest: umc-web.env
    - src: env/umc-gateway.env.j2
      dest: umc-gateway.env
    - src: env/umc-server.env.j2
      dest: umc-server.env
    - src: umc/server/ucr.j2
      dest: umc/server/ucr
    - src: umc/gateway/ucr.j2
      dest: umc/gateway/ucr
    - src: umc/web/ucr.j2
      dest: umc/web/ucr

- name: Copy secret files
  ansible.builtin.template:
    src: config-secret.j2
    dest: "{{ openldap_secrets_directory }}/{{ item.filename }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - filename: CAcert.pem
      secret: "{{ openldap_cacert_pem }}"
    - filename: cert.pem
      secret: "{{ openldap_cert_pem }}"
    - filename: private.key
      secret: "{{ openldap_private_key }}"
    - filename: dh_2048.pem
      secret: "{{ openldap_dh_parameters }}"
  no_log: true
