---
- name: Include distribution specific install tasks
  ansible.builtin.include_tasks: "install-server-{{ ansible_os_family }}.yml"

- name: Create systemd overlay directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/cockpit.socket.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy systemd overlay file
  become: true
  ansible.builtin.template:
    src: listen.conf.j2
    dest: /etc/systemd/system/cockpit.socket.d/listen.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart cockpit.socket service

- name: Copy configuration file
  become: true
  ansible.builtin.copy:
    src: cockpit.conf
    dest: /etc/cockpit/cockpit.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart cockpit service

- name: Start/enable required services
  become: true
  ansible.builtin.systemd:
    enabled: true
    state: started
    daemon_reload: true
    name: "{{ item }}"
  loop:
    - cockpit
    - cockpit.socket

- name: Copy machine files
  become: true
  ansible.builtin.template:
    src: machine.json.j2
    dest: "/etc/cockpit/machines.d/05-osism-{{ item }}.json"
    owner: root
    group: root
    mode: 0644
  loop: "{{ groups[cockpit_groupname]|default([]) }}"
  when: item != inventory_hostname
