---
- name: Create traefik external network
  become: true
  community.docker.docker_network:
    name: "{{ traefik_external_network_name }}"
    ipam_config:
      - subnet: "{{ traefik_external_network_cidr }}"
  when: keycloak_traefik|bool

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ keycloak_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart keycloak service

- name: Start/enable keycloak service
  become: true
  ansible.builtin.service:
    name: "{{ keycloak_service_name }}"
    state: started
    enabled: true
  register: keycloak_service
