---
##########################
# operator

operator_user: dragon
operator_group: "{{ operator_user }}"

##########################
# docker

docker_registry_patchman: quay.io
docker_registry_postgres: index.docker.io
docker_registry_memcached: index.docker.io

##########################
# patchman

patchman_configuration_directory: /opt/patchman/configuration
patchman_docker_compose_directory: /opt/patchman

patchman_host: 127.0.0.1
patchman_port: 8150

patchman_tag: latest
patchman_image: "{{ docker_registry_patchman }}/osism/patchman:{{ patchman_tag }}"

patchman_container_name: patchman

patchman_network: 172.31.100.80/28

patchman_service_name: "docker-compose@patchman"

patchman_username: patchman
patchman_password: password

patchman_secret_key: aiGe7eedievootee3ook3aeshok2sa4p

patchman_cron_day: "*"
patchman_cron_hour: "1"
patchman_cron_minute: "3"
patchman_cron_user: "{{ operator_user|default('dragon') }}"

patchman_debug: "False"

patchman_update_statfile: /tmp/patchman.stat
patchman_update: true
patchman_update_force: false
patchman_update_valid_time: 86400

##########################
# postgres

postgres_tag: 13-alpine
postgres_image: "{{ docker_registry_postgres }}/library/postgres:{{ postgres_tag }}"

patchman_postgres_username: patchman
patchman_postgres_password: password
patchman_postgres_databasename: "{{ patchman_postgres_username }}"

##########################
# memcached

patchman_memcached_tag: alpine
patchman_memcached_image: "{{ docker_registry_memcached }}/library/memcached:{{ patchman_memcached_tag }}"
