---
galaxy_info:
  author: Tim Beermann
  description: Role osism.services.squid
  company: OSISM GmbH
  license: Apache License 2.0
  min_ansible_version: 2.13.0
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - osism
    - system
dependencies: []
