---
- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  when: netdata_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  become: true
  ansible.builtin.apt_key:
    url: "{{ netdata_debian_repository_key }}"
  when: netdata_configure_repository|bool

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ netdata_debian_repository }}"
    state: present
    filename: netdata
    update_cache: true
    mode: 0644
  when: netdata_configure_repository|bool

- name: "Install {{ netdata_package_name }} package"
  become: true
  ansible.builtin.apt:
    name: "{{ netdata_package_name }}"
    state: latest
  notify: "Restart {{ netdata_service_name }} service"

- name: "Start/enable {{ netdata_service_name }} service"
  become: true
  ansible.builtin.service:
    name: "{{ netdata_service_name }}"
    state: started
    enabled: true
