---
containerd_package_name: containerd.io
containerd_service_name: containerd
containerd_grpc_gid: 42463

containerd_packages_fail:
  - containerd

##########################
# repository

docker_configure_repository: true

docker_debian_repository_key: https://download.docker.com/linux/ubuntu/gpg
docker_debian_repository: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
