---
patchman_client_cron_day: "*"
patchman_client_cron_hour: "0"
patchman_client_cron_minute: "3"
patchman_client_cron_user: "{{ operator_user|default('dragon') }}"

patchman_client_curl_options: "--insecure --connect-timeout 60 --max-time 300"
patchman_client_report: 0
patchman_client_tags: Server

patchman_client_host: localhost
patchman_client_port: 8150
patchman_client_server_url: "http://{{ patchman_client_host }}:{{ patchman_client_port }}"

patchman_client_update_statfile: /tmp/patchman-client.stat
patchman_client_update: true
patchman_client_update_force: false
patchman_client_update_valid_time: 86400
