---
galaxy_info:
  author: Christian Berendt
  description: Role osism.services.teleport
  company: OSISM GmbH
  license: Apache License 2.0
  min_ansible_version: 2.16.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - osism
    - system
dependencies: []
