---
- name: Create required directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  loop:
    - "{{ metering_configuration_directory }}"
    - "{{ metering_data_directory }}"
    - "{{ metering_docker_compose_directory }}"

- name: Copy settings.conf file
  ansible.builtin.template:
    src: settings.conf.j2
    dest: "{{ metering_configuration_directory }}/settings.conf"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart metering service

- name: Copy docker-compose.yml file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ metering_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart metering service

- name: Start/enable metering service
  become: true
  ansible.builtin.service:
    name: "{{ metering_service_name }}"
    state: started
    enabled: true
