---
# client

configure_cockpit: true

cockpit_groupname: all

cockpit_system_color: yellow
cockpit_system_visible: "true"

# server

configure_cockpit_server: false

cockpit_groupname_server: manager

cockpit_host: 127.0.0.1
cockpit_port: 8130

cockpit_ssh_port: 22
cockpit_ssh_interface: ens3
