---
galaxy_info:
  author: Eike Waldt
  description: Role osism.services.rook_operator
  company: OSISM GmbH
  license: Apache License 2.0
  min_ansible_version: 2.16.0
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - "9"
  galaxy_tags:
    - osism
    - kubernetes
    - helm
