---
- name: Copy AWX helper scripts
  ansible.builtin.copy:
    src: "awx/{{ item }}"
    dest: "{{ manager_configuration_directory }}/{{ item }}"
    mode: 0755
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - create-admin-user.sh
    - provision-instance.sh

- name: Copy AWX environment files
  ansible.builtin.template:
    src: "env/{{ item }}.env.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}.env"
    mode: 0640
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - awx
    - awxclient

- name: Copy AWX configuration files
  ansible.builtin.template:
    src: "awx/{{ item }}.j2"
    dest: "{{ manager_configuration_directory }}/{{ item }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - credentials.py
    - nginx.conf
    - receptor.conf
    - settings.py
    - supervisord.conf

- name: Copy secret files
  ansible.builtin.copy:
    content: "{{ item.secret }}"
    dest: "{{ manager_secrets_directory }}/{{ item.filename }}"
    mode: 0644
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
  loop:
    - filename: TOWER_PASSWORD
      secret: "{{ awx_password }}"
    - filename: TOWER_USERNAME
      secret: "{{ awx_username }}"
    - filename: TOWER_SECRET_KEY
      secret: "{{ awx_secret_key }}"
  no_log: true
