---
##########################
# services

osquery_service_name: osqueryd

##########################
# packages

osquery_package_name: osquery

##########################
# repository

osquery_configure_repository: true

osquery_debian_repository_key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1484120ac4e9f8a1a577aeee97a80c63c9d8b80b"
osquery_debian_repository: "deb https://pkg.osquery.io/deb deb main"
