---
- name: Create filesystem on storage block device  # noqa: ignore-errors
  become: true
  community.general.filesystem:
    dev: "{{ docker_storage_block_device }}"
    fstype: "{{ docker_storage_filesystem }}"
    force: "{{ docker_storage_force }}"
  ignore_errors: true

- name: Create docker directory
  become: true
  ansible.builtin.file:
    path: /var/lib/docker
    state: directory
    owner: root
    group: root
    mode: 0711
  tags:
    - skip_ansible_lint

- name: Mount storage block device to docker directory
  become: true
  ansible.posix.mount:
    path: /var/lib/docker
    src: "{{ docker_storage_block_device }}"
    fstype: "{{ docker_storage_filesystem }}"
    state: mounted
