---
- name: Install apt-transport-https package
  become: true
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  when: osquery_configure_repository|bool
  changed_when: false

- name: Add repository gpg key
  become: true
  ansible.builtin.apt_key:
    url: "{{ osquery_debian_repository_key }}"
  when: osquery_configure_repository|bool

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ osquery_debian_repository }}"
    state: present
    filename: osquery
    update_cache: true
  when: osquery_configure_repository|bool

- name: "Install {{ osquery_package_name }} package"
  become: true
  ansible.builtin.apt:
    name: "{{ osquery_package_name }}"
    state: latest
  notify: "Restart {{ osquery_service_name }} service"

- name: "Start/enable {{ osquery_service_name }} service"
  become: true
  ansible.builtin.service:
    name: "{{ osquery_service_name }}"
    state: started
    enabled: true
