---
- name: Copy hddtemp configuration file
  become: true
  ansible.builtin.copy:
    src: "{{ ansible_os_family }}/hddtemp"
    dest: "{{ hddtemp_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart hddtemp service
  when:
    - ansible_distribution_version is version('22.04', '<')

- name: Start/enable hddtemp service
  become: true
  ansible.builtin.service:
    name: hddtemp
    state: started
    enabled: true
  when:
    - ansible_distribution_version is version('22.04', '<')

- name: Start/enable lm-sensors service
  become: true
  ansible.builtin.service:
    name: lm-sensors
    state: started
    enabled: true
  when:
    - ansible_distribution_version is version('22.04', '>=')
