---
- name: Add repository key
  become: true
  ansible.builtin.apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ openstackclient_debian_repository_key }}"
  when: openstackclient_configure_repository|bool

- name: Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ openstackclient_debian_repository }}"
    state: present
    update_cache: true
    mode: 0644
  when: openstackclient_configure_repository|bool

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name: "{{ openstackclient_debian_packages }}"
    state: present
