---
##########################
# operator

operator_user: dragon
operator_group: "{{ operator_user }}"

##########################
# docker

docker_network_mtu: 1500

docker_registry_openldap: quay.io
docker_registry_udm_rest: quay.io
docker_registry_umc: quay.io

##########################
# openldap

openldap_configuration_directory: /opt/openldap/configuration
openldap_secrets_directory: /opt/openldap/secrets
openldap_docker_compose_directory: /opt/openldap

openldap_network: 172.31.100.240/28
openldap_container_name: openldap
openldap_service_name: "docker-compose@openldap"

openldap_host: 127.0.0.1
openldap_ldap_port: 389
openldap_ldaps_port: 636

openldap_tag: build-25862
openldap_image: "{{ docker_registry_openldap }}/univention/upx-ldap-server:{{ openldap_tag }}"

openldap_domain_name: osism.local
openldap_base_dn: dc=osism,dc=local

# openldap_user: cn=admin,{{ openldap_base_dn }}
openldap_password: password

openldap_cacert_pem: '-----BEGIN CERTIFICATE-----

  MIIDmzCCAoOgAwIBAgIUDKffrgs82WVxZBr/RQfgWMdx6EYwDQYJKoZIhvcNAQEL

  BQAwXTELMAkGA1UEBhMCREUxDzANBgNVBAgMBkJyZW1lbjEPMA0GA1UEBwwGQnJl

  bWVuMRMwEQYDVQQKDApVbml2ZW50aW9uMRcwFQYDVQQDDA5hcGkub3Npc20udGVz

  dDAeFw0yMTA2MDcxNDEwMThaFw0yNjA2MDYxNDEwMThaMF0xCzAJBgNVBAYTAkRF

  MQ8wDQYDVQQIDAZCcmVtZW4xDzANBgNVBAcMBkJyZW1lbjETMBEGA1UECgwKVW5p

  dmVudGlvbjEXMBUGA1UEAwwOYXBpLm9zaXNtLnRlc3QwggEiMA0GCSqGSIb3DQEB

  AQUAA4IBDwAwggEKAoIBAQCauHESdfGs7uUUiN5uKTTKv/HGITeafTRMF9Vd9THE

  /8u3iD16YoTAD07GOiHCrZSkZXUFqIa6RA42+bN0n5gpCzFR+TMPvOQZxNxC2t18

  Ejps0Q1xwXQ0LlWykiwRwpuAvtMbv/qliODsVH2QcZ1e43Z5IHOw8Z1KA13iivRu

  RzDH6/fo7VsygCoNlUdBdU2+G7qVuxX5Sj83ay1x49TryItTZlEINEHQnudjNUga

  dS9jzWwZkx8Wx8rHhXQc4tUFafqL1OJqw7Hd6087gondHm8JrlbeGmtwLO+iIoxr

  nvI68TNMN7x7kLfLZz/8KGEzBEbi3oJjG+yWxizJzWS7AgMBAAGjUzBRMB0GA1Ud

  DgQWBBSeFH6RE1ucZohz9KLfLw6rVCgrRTAfBgNVHSMEGDAWgBSeFH6RE1ucZohz

  9KLfLw6rVCgrRTAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBz

  CSEHnO/7B4vprvqLWcdtOpNyY1bNljqOyUb6cXTrHQvVc9IhlIBu7YGZBzYSIPZf

  vny7J8CMkQL+dGTHrkNZTBX3Jl6Bzvu11mC2lqDmB4e6AyaGvuXMe67XMoTz0roq

  UK+GUCuWWlkeeMT1hZuvukERTMAfF6okNQ4uarKJrPiyOx+GONzfShjAFTSZX1oD

  S1C1rp++EjHN2l7OU14c6UFgCsBhAMTqQl/Yq7QE2/trr/bv+GobC0XyyaFF8iy2

  G/u7AF5On/vvmDajdbK6q8CxgUdJXgrOFh5kpJ6TkZgW7K2ycTGyJoLW8f+CaL5E

  JSrE5URe7j73IXZZ3m6m

  -----END CERTIFICATE-----
  '
openldap_cert_pem: '-----BEGIN CERTIFICATE-----

  MIIDVjCCAj4CFBFVw5yHY+PLiq4y7GSdY/rnKISJMA0GCSqGSIb3DQEBCwUAMF0x

  CzAJBgNVBAYTAkRFMQ8wDQYDVQQIDAZCcmVtZW4xDzANBgNVBAcMBkJyZW1lbjET

  MBEGA1UECgwKVW5pdmVudGlvbjEXMBUGA1UEAwwOYXBpLm9zaXNtLnRlc3QwHhcN

  MjEwNjA3MTQxMTU2WhcNMjYwNjA2MTQxMTU2WjByMQswCQYDVQQGEwJERTEPMA0G

  A1UECAwGQnJlbWVuMQ8wDQYDVQQHDAZCcmVtZW4xKDAmBgNVBAoMH1VuaXZlbnRp

  b24bW0EbW0EbW0EbW0EbW0EbW0EbW0ExFzAVBgNVBAMMDmFwaS5vc2lzbS50ZXN0

  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmrhxEnXxrO7lFIjebik0

  yr/xxiE3mn00TBfVXfUxxP/Lt4g9emKEwA9Oxjohwq2UpGV1BaiGukQONvmzdJ+Y

  KQsxUfkzD7zkGcTcQtrdfBI6bNENccF0NC5VspIsEcKbgL7TG7/6pYjg7FR9kHGd

  XuN2eSBzsPGdSgNd4or0bkcwx+v36O1bMoAqDZVHQXVNvhu6lbsV+Uo/N2stcePU

  68iLU2ZRCDRB0J7nYzVIGnUvY81sGZMfFsfKx4V0HOLVBWn6i9TiasOx3etPO4KJ

  3R5vCa5W3hprcCzvoiKMa57yOvEzTDe8e5C3y2c//ChhMwRG4t6CYxvslsYsyc1k

  uwIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAASCgMg5OCM507ebFhEgUXLIjBCL+V

  BC76qHlinekcJWBwIXP1mrXqRd1vtE/KOampL/JvM9OjtLURxRvf+t/vqBPmA1X6

  95MTrf7HFxEoytilXOZr799psBtTTZ0CmW/7wErhDKHVQ/SF8d5w9tRGCGVigrl7

  gZC1tP9fxqJlc92JdgwYKJeABsbr0yiRLw4/8BsGyDpPTwXJDmZX0ta0adObUZLR

  yTq3TbJnneqHSqvQnf3B304hzGzOVGcqkZHoQASUUxp17rGKMEl5Zq9fp3jH7Rjy

  1MyZGFLsIfCKkpdyzbzoAqG4Z2Vxslnlyb1mva/SVyA5U7WkpMrWCYhv

  -----END CERTIFICATE-----
  '
openldap_private_key: '-----BEGIN RSA PRIVATE KEY-----

  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCauHESdfGs7uUU

  iN5uKTTKv/HGITeafTRMF9Vd9THE/8u3iD16YoTAD07GOiHCrZSkZXUFqIa6RA42

  +bN0n5gpCzFR+TMPvOQZxNxC2t18Ejps0Q1xwXQ0LlWykiwRwpuAvtMbv/qliODs

  VH2QcZ1e43Z5IHOw8Z1KA13iivRuRzDH6/fo7VsygCoNlUdBdU2+G7qVuxX5Sj83

  ay1x49TryItTZlEINEHQnudjNUgadS9jzWwZkx8Wx8rHhXQc4tUFafqL1OJqw7Hd

  6087gondHm8JrlbeGmtwLO+iIoxrnvI68TNMN7x7kLfLZz/8KGEzBEbi3oJjG+yW

  xizJzWS7AgMBAAECggEAAvvrsl9z+dHhuTOqlpVU31Q0ZY3edKxVheIvy1AfVZ1Z

  YIDQLrwXs1yYOFqGrCqM417RkvpdHtqRK55FR8qMNL5yhRI5WeRaweR6Gw/9lZcE

  aXTevYLtqtP58ye+kdkfBqynhbF+NBMfw28dvNt0HZBliJCHqrH+Rp8qAGSNslLF

  f50S3OXFoy5Q6hfluJW6Q1SX06U3GYKpY/lSPGe3HmWVbfnPVBLzzEA3Ik/BESJs

  //ir/cAE+LZUd2AvmmIWXXVW1MdoXZP+Gg9qhzh6W8x8mYBSK6WM9iOn0d7xWsup

  5Wuaxlal/VqE5sHj4FX8RpUB35PWJh/BNgonQzdfAQKBgQDN+pSoB/xlZN9Naksi

  LCF6iS6UPu/3mN2raO7xFDP+3NGt4h0Vvqc4f1ZC5IzCabXr4u3yHvQPz+NVENfM

  WrlySnU4s90Sp0LpD1eE13ARSfo7F+VhEh9JoIs8qf4bZSASuuZPLO5SHD19z/n/

  vQTqL13r2O1OgMcJPH88fRnwowKBgQDASzMqNq+i+jHa70bxIzYVbD8kq6VMAHjz

  rYfwrK8fWinwKiYhyrWRlIWG0YQxQdzOXBQkbNjWa31VxfBK4jlvyMnDCO6rG7v9

  DKZN6FL2Fp2kJkG8SMwFhPmbKp7tbsux6d18CFCj5BUzPhoVq1GEq+V0CMkoJS/B

  xicUelhFCQKBgF0H8Fx0PusMxE6S05x7kiNmEkOiqX+K65OfsUvxdAqIcau3lKtd

  kOlTmgJcd7bXR/Nia1YP5Ou/WU3ybYU+9MNKHeeeVRs3sGDTLRQyucsVPo+yG0fc

  h4UZncmofbyhz/qlr5/TC1DKsHtClAeNt8qN2j3LnGL4hu0FBfKsDitBAoGAEVu4

  dqsRF8k2Duliognnq+9lk83a0g2I3ZZgmx07gb0F5CQp5QsDcOzTUORA5qFnaUlu

  mAsrV8/ENKX1lwzs2mZpsC1yPgf25FTr/kRmmMhZ2qOJc5GuuSDT12n1hsFlqd3O

  nI+zl9fTAhktCZ+5cByETgEtB26z7O4SQQr6ROECgYEAidbtiYB/ptSe7pS7YWBl

  cdtirGCYiV3HKPbJhZYPbiSewvOr+OxKNgQdditD8BNaLVimIoSmgiElD36vgbPR

  7aVqN0QqNUHXAvLVS9Qxg8BiK1v+1qQER3P1908HDbjy6MDCLhLRzktCSo8Oitb6

  IB0InrBc0kUPxm3W/WV6aoE=

  -----END RSA PRIVATE KEY-----
  '
openldap_dh_parameters: '-----BEGIN DH PARAMETERS-----

  MIIBCAKCAQEA43/0ZU5Uh9R8BS2xEWXn0vZBZaNGVxr6X8/4pWsQJJxZqv/yUZkg

  Bg/MRhWgm5At3v++5pJcLsxjGzDL21EvalSeG8GHQukBSnafuXO5BzCvPAGhgitF

  tDYybueOFkrr8k9hQMGsfJd4i2sTgCI8azrrPaKPZFDnSM6qTHalFuXhHSD75MDO

  o4CpWuCEw8EDhaM3iUHDPY1JlAK7PeX5XGZRJ21tXM+6lmYJqfhMZdSuOjcAMRZ/

  Ym5L9/xs036ntyJU6UwZxERE2C1Xdr6XAsxLMUTIgJd6xwb/dOcraPzu5SI75puM

  /VCSVSynA0mwFBSfEbpaePIifVAVnF64iwIBAg==

  -----END DH PARAMETERS-----
  '

##########################
# UDM

udm_rest_host: 127.0.0.1
udm_rest_port: 9979

udm_rest_container_name: udm-rest
udm_rest_tag: build-24328
udm_rest_image: "{{ docker_registry_udm_rest }}/univention/upx-udm-rest:{{ udm_rest_tag }}"

##########################
# UMC

umc_web_host: 127.0.0.1
umc_web_port: 8090

umc_web_container_name: umc-web
umc_web_tag: build-24437
umc_web_image: "{{ docker_registry_umc }}/univention/upx-umc-web:{{ umc_web_tag }}"

umc_gateway_host: 127.0.0.1
umc_gateway_http_port: 8191
umc_gateway_https_port: 8192

umc_gateway_container_name: umc-gateway
umc_gateway_tag: build-24437
umc_gateway_image: "{{ docker_registry_umc }}/univention/upx-umc-gateway:{{ umc_gateway_tag }}"

umc_server_host: 127.0.0.1
umc_server_port: 6670

umc_server_container_name: umc-server
umc_server_tag: build-24437
umc_server_image: "{{ docker_registry_umc }}/univention/upx-umc-server:{{ umc_server_tag }}"
