---
name: Test role lldpd

"on":
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/test-role-lldpd.yml'
      - 'molecule/delegated/*'
      - 'molecule/lldpd/**'
      - 'roles/lldpd/**'
    branches:
      - main
  pull_request:
    paths:
      - '.github/workflows/test-role-lldpd.yml'
      - 'molecule/delegated/*'
      - 'molecule/lldpd/**'
      - 'roles/lldpd/**'

jobs:
  test-role-lldpd:

    runs-on: ubuntu-latest

    env:
      ANSIBLE_ROLE: lldpd

    strategy:
      max-parallel: 4
      matrix:
        ansible-version: ['5.9.0']
        python-version: ['3.8']
        docker-image: ['ubuntu:20.04']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      # NOTE: Technically, Molecule supports variable interpolation in molecule.yml.
      #       For reasons that are not really comprehensible, however, it does not
      #       work here. Hence this workaround.
      - name: Prepare molecule.yml
        run: |
          sed -i "s/\${DOCKER_IMAGE}/${{ matrix.docker-image }}/g" molecule/delegated/molecule.yml
          sed -i "s/\${ANSIBLE_ROLE}/${{ env.ANSIBLE_ROLE }}/g" molecule/delegated/molecule.yml
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r molecule/requirements.txt
          python3 -m pip install ansible~=${{ matrix.ansible-version }}
      - name: Run molecule
        run: molecule test -s delegated
      - name: Cleanup molecule
        run: molecule destroy -s delegated
        if: ${{ always() }}
